service:
  type: ${service_type}
ingress:
  enabled: true
  hostRepo: ${ingress_hostname}
  tls:
  - hosts: 
    - ${ingress_hostname}
persistence:
  storageClass: ${storage_class}
  storageSize: ${storage_size}
nexus:
  docker:
    enabled: true
  env:
    - name: INSTALL4J_ADD_VM_PARAMS
      value: "-Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    - name: NEXUS_SECURITY_RANDOMPASSWORD
      value: "false"
  